# For the outbounds proxy

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
http_access deny !Safe_ports

acl allowed_domains dstdomain .deepseek.com
acl allowed_domains dstdomain .openai.com
acl allowed_domains dstdomain .anthropic.com
acl allowed_domains dstdomain .github.com
acl allowed_domains dstdomain huggingface.co

http_access deny !allowed_domains
http_access allow allowed_domains

http_access deny all

http_port 3128
